// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/analytics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetPortfolioAnalytics_FullMethodName = "/analytics.AnalyticsService/GetPortfolioAnalytics"
	AnalyticsService_GetRiskMetrics_FullMethodName        = "/analytics.AnalyticsService/GetRiskMetrics"
	AnalyticsService_GetCorrelationMatrix_FullMethodName  = "/analytics.AnalyticsService/GetCorrelationMatrix"
	AnalyticsService_GetTradingSignals_FullMethodName     = "/analytics.AnalyticsService/GetTradingSignals"
	AnalyticsService_GetPerformanceMetrics_FullMethodName = "/analytics.AnalyticsService/GetPerformanceMetrics"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	// Get portfolio analytics
	GetPortfolioAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*PortfolioAnalytics, error)
	// Get risk metrics for symbols
	GetRiskMetrics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RiskMetrics], error)
	// Get correlation matrix
	GetCorrelationMatrix(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*CorrelationMatrix, error)
	// Get trading signals
	GetTradingSignals(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradingSignal], error)
	// Get performance comparison metrics
	GetPerformanceMetrics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*PerformanceMetrics, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetPortfolioAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*PortfolioAnalytics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioAnalytics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPortfolioAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetRiskMetrics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RiskMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyticsService_ServiceDesc.Streams[0], AnalyticsService_GetRiskMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyticsRequest, RiskMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetRiskMetricsClient = grpc.ServerStreamingClient[RiskMetrics]

func (c *analyticsServiceClient) GetCorrelationMatrix(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*CorrelationMatrix, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrelationMatrix)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCorrelationMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTradingSignals(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TradingSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalyticsService_ServiceDesc.Streams[1], AnalyticsService_GetTradingSignals_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyticsRequest, TradingSignal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetTradingSignalsClient = grpc.ServerStreamingClient[TradingSignal]

func (c *analyticsServiceClient) GetPerformanceMetrics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*PerformanceMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceMetrics)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPerformanceMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	// Get portfolio analytics
	GetPortfolioAnalytics(context.Context, *AnalyticsRequest) (*PortfolioAnalytics, error)
	// Get risk metrics for symbols
	GetRiskMetrics(*AnalyticsRequest, grpc.ServerStreamingServer[RiskMetrics]) error
	// Get correlation matrix
	GetCorrelationMatrix(context.Context, *AnalyticsRequest) (*CorrelationMatrix, error)
	// Get trading signals
	GetTradingSignals(*AnalyticsRequest, grpc.ServerStreamingServer[TradingSignal]) error
	// Get performance comparison metrics
	GetPerformanceMetrics(context.Context, *AnalyticsRequest) (*PerformanceMetrics, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetPortfolioAnalytics(context.Context, *AnalyticsRequest) (*PortfolioAnalytics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortfolioAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetRiskMetrics(*AnalyticsRequest, grpc.ServerStreamingServer[RiskMetrics]) error {
	return status.Error(codes.Unimplemented, "method GetRiskMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCorrelationMatrix(context.Context, *AnalyticsRequest) (*CorrelationMatrix, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCorrelationMatrix not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTradingSignals(*AnalyticsRequest, grpc.ServerStreamingServer[TradingSignal]) error {
	return status.Error(codes.Unimplemented, "method GetTradingSignals not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPerformanceMetrics(context.Context, *AnalyticsRequest) (*PerformanceMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPerformanceMetrics not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetPortfolioAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPortfolioAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPortfolioAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPortfolioAnalytics(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetRiskMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).GetRiskMetrics(m, &grpc.GenericServerStream[AnalyticsRequest, RiskMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetRiskMetricsServer = grpc.ServerStreamingServer[RiskMetrics]

func _AnalyticsService_GetCorrelationMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCorrelationMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCorrelationMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCorrelationMatrix(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTradingSignals_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).GetTradingSignals(m, &grpc.GenericServerStream[AnalyticsRequest, TradingSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalyticsService_GetTradingSignalsServer = grpc.ServerStreamingServer[TradingSignal]

func _AnalyticsService_GetPerformanceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPerformanceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPerformanceMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPerformanceMetrics(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolioAnalytics",
			Handler:    _AnalyticsService_GetPortfolioAnalytics_Handler,
		},
		{
			MethodName: "GetCorrelationMatrix",
			Handler:    _AnalyticsService_GetCorrelationMatrix_Handler,
		},
		{
			MethodName: "GetPerformanceMetrics",
			Handler:    _AnalyticsService_GetPerformanceMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRiskMetrics",
			Handler:       _AnalyticsService_GetRiskMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTradingSignals",
			Handler:       _AnalyticsService_GetTradingSignals_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/analytics.proto",
}
