// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for analytics data
type AnalyticsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbols           []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	TimeWindowMinutes int32                  `protobuf:"varint,2,opt,name=time_window_minutes,json=timeWindowMinutes,proto3" json:"time_window_minutes,omitempty"` // How far back to analyze
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AnalyticsRequest) GetTimeWindowMinutes() int32 {
	if x != nil {
		return x.TimeWindowMinutes
	}
	return 0
}

// Portfolio analytics
type PortfolioAnalytics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Symbols             []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	TotalValue          float64                `protobuf:"fixed64,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalReturn         float64                `protobuf:"fixed64,3,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty"`
	PortfolioVolatility float64                `protobuf:"fixed64,4,opt,name=portfolio_volatility,json=portfolioVolatility,proto3" json:"portfolio_volatility,omitempty"`
	SharpeRatio         float64                `protobuf:"fixed64,5,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"`
	ValueAtRisk_95      float64                `protobuf:"fixed64,6,opt,name=value_at_risk_95,json=valueAtRisk95,proto3" json:"value_at_risk_95,omitempty"` // VaR at 95% confidence
	ValueAtRisk_99      float64                `protobuf:"fixed64,7,opt,name=value_at_risk_99,json=valueAtRisk99,proto3" json:"value_at_risk_99,omitempty"` // VaR at 99% confidence
	Timestamp           int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PortfolioAnalytics) Reset() {
	*x = PortfolioAnalytics{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioAnalytics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioAnalytics) ProtoMessage() {}

func (x *PortfolioAnalytics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioAnalytics.ProtoReflect.Descriptor instead.
func (*PortfolioAnalytics) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioAnalytics) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *PortfolioAnalytics) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PortfolioAnalytics) GetTotalReturn() float64 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *PortfolioAnalytics) GetPortfolioVolatility() float64 {
	if x != nil {
		return x.PortfolioVolatility
	}
	return 0
}

func (x *PortfolioAnalytics) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *PortfolioAnalytics) GetValueAtRisk_95() float64 {
	if x != nil {
		return x.ValueAtRisk_95
	}
	return 0
}

func (x *PortfolioAnalytics) GetValueAtRisk_99() float64 {
	if x != nil {
		return x.ValueAtRisk_99
	}
	return 0
}

func (x *PortfolioAnalytics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Risk metrics for a single symbol
type RiskMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Symbol         string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Volatility     float64                `protobuf:"fixed64,2,opt,name=volatility,proto3" json:"volatility,omitempty"`                      // Price volatility %
	SharpeRatio    float64                `protobuf:"fixed64,3,opt,name=sharpe_ratio,json=sharpeRatio,proto3" json:"sharpe_ratio,omitempty"` // Risk-adjusted return
	Beta           float64                `protobuf:"fixed64,4,opt,name=beta,proto3" json:"beta,omitempty"`                                  // Relative to market
	ValueAtRisk_95 float64                `protobuf:"fixed64,5,opt,name=value_at_risk_95,json=valueAtRisk95,proto3" json:"value_at_risk_95,omitempty"`
	ValueAtRisk_99 float64                `protobuf:"fixed64,6,opt,name=value_at_risk_99,json=valueAtRisk99,proto3" json:"value_at_risk_99,omitempty"`
	MaxDrawdown    float64                `protobuf:"fixed64,7,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"`          // Largest peak-to-trough decline
	ExpectedReturn float64                `protobuf:"fixed64,8,opt,name=expected_return,json=expectedReturn,proto3" json:"expected_return,omitempty"` // Annualized return estimate
	Timestamp      int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RiskMetrics) Reset() {
	*x = RiskMetrics{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskMetrics) ProtoMessage() {}

func (x *RiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskMetrics.ProtoReflect.Descriptor instead.
func (*RiskMetrics) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *RiskMetrics) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RiskMetrics) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *RiskMetrics) GetSharpeRatio() float64 {
	if x != nil {
		return x.SharpeRatio
	}
	return 0
}

func (x *RiskMetrics) GetBeta() float64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *RiskMetrics) GetValueAtRisk_95() float64 {
	if x != nil {
		return x.ValueAtRisk_95
	}
	return 0
}

func (x *RiskMetrics) GetValueAtRisk_99() float64 {
	if x != nil {
		return x.ValueAtRisk_99
	}
	return 0
}

func (x *RiskMetrics) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *RiskMetrics) GetExpectedReturn() float64 {
	if x != nil {
		return x.ExpectedReturn
	}
	return 0
}

func (x *RiskMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Correlation between two symbols
type CorrelationPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol1       string                 `protobuf:"bytes,1,opt,name=symbol1,proto3" json:"symbol1,omitempty"`
	Symbol2       string                 `protobuf:"bytes,2,opt,name=symbol2,proto3" json:"symbol2,omitempty"`
	Correlation   float64                `protobuf:"fixed64,3,opt,name=correlation,proto3" json:"correlation,omitempty"` // -1 to 1
	SampleSize    int32                  `protobuf:"varint,4,opt,name=sample_size,json=sampleSize,proto3" json:"sample_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelationPair) Reset() {
	*x = CorrelationPair{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationPair) ProtoMessage() {}

func (x *CorrelationPair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationPair.ProtoReflect.Descriptor instead.
func (*CorrelationPair) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *CorrelationPair) GetSymbol1() string {
	if x != nil {
		return x.Symbol1
	}
	return ""
}

func (x *CorrelationPair) GetSymbol2() string {
	if x != nil {
		return x.Symbol2
	}
	return ""
}

func (x *CorrelationPair) GetCorrelation() float64 {
	if x != nil {
		return x.Correlation
	}
	return 0
}

func (x *CorrelationPair) GetSampleSize() int32 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

// Correlation matrix
type CorrelationMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Pairs         []*CorrelationPair     `protobuf:"bytes,2,rep,name=pairs,proto3" json:"pairs,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CorrelationMatrix) Reset() {
	*x = CorrelationMatrix{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CorrelationMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationMatrix) ProtoMessage() {}

func (x *CorrelationMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationMatrix.ProtoReflect.Descriptor instead.
func (*CorrelationMatrix) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *CorrelationMatrix) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *CorrelationMatrix) GetPairs() []*CorrelationPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *CorrelationMatrix) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Trading signal
type TradingSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SignalType    string                 `protobuf:"bytes,2,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"` // "BUY", "SELL", "HOLD"
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                 // 0-1
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                           // Why this signal
	TargetPrice   float64                `protobuf:"fixed64,5,opt,name=target_price,json=targetPrice,proto3" json:"target_price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradingSignal) Reset() {
	*x = TradingSignal{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingSignal) ProtoMessage() {}

func (x *TradingSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingSignal.ProtoReflect.Descriptor instead.
func (*TradingSignal) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *TradingSignal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TradingSignal) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *TradingSignal) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TradingSignal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TradingSignal) GetTargetPrice() float64 {
	if x != nil {
		return x.TargetPrice
	}
	return 0
}

func (x *TradingSignal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Performance metrics (for benchmarking)
type PerformanceMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApiType         string                 `protobuf:"bytes,1,opt,name=api_type,json=apiType,proto3" json:"api_type,omitempty"` // "gRPC" or "REST"
	AvgLatencyMs    float64                `protobuf:"fixed64,2,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P50LatencyMs    float64                `protobuf:"fixed64,3,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs    float64                `protobuf:"fixed64,4,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs    float64                `protobuf:"fixed64,5,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	RequestCount    int64                  `protobuf:"varint,6,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	ThroughputRps   float64                `protobuf:"fixed64,7,opt,name=throughput_rps,json=throughputRps,proto3" json:"throughput_rps,omitempty"` // Requests per second
	AvgPayloadBytes int64                  `protobuf:"varint,8,opt,name=avg_payload_bytes,json=avgPayloadBytes,proto3" json:"avg_payload_bytes,omitempty"`
	Timestamp       int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PerformanceMetrics) Reset() {
	*x = PerformanceMetrics{}
	mi := &file_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetrics) ProtoMessage() {}

func (x *PerformanceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetrics.ProtoReflect.Descriptor instead.
func (*PerformanceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *PerformanceMetrics) GetApiType() string {
	if x != nil {
		return x.ApiType
	}
	return ""
}

func (x *PerformanceMetrics) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *PerformanceMetrics) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *PerformanceMetrics) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *PerformanceMetrics) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *PerformanceMetrics) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *PerformanceMetrics) GetThroughputRps() float64 {
	if x != nil {
		return x.ThroughputRps
	}
	return 0
}

func (x *PerformanceMetrics) GetAvgPayloadBytes() int64 {
	if x != nil {
		return x.AvgPayloadBytes
	}
	return 0
}

func (x *PerformanceMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\tanalytics\x1a\x15proto/processor.proto\"\\\n" +
	"\x10AnalyticsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12.\n" +
	"\x13time_window_minutes\x18\x02 \x01(\x05R\x11timeWindowMinutes\"\xb8\x02\n" +
	"\x12PortfolioAnalytics\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x01R\n" +
	"totalValue\x12!\n" +
	"\ftotal_return\x18\x03 \x01(\x01R\vtotalReturn\x121\n" +
	"\x14portfolio_volatility\x18\x04 \x01(\x01R\x13portfolioVolatility\x12!\n" +
	"\fsharpe_ratio\x18\x05 \x01(\x01R\vsharpeRatio\x12'\n" +
	"\x10value_at_risk_95\x18\x06 \x01(\x01R\rvalueAtRisk95\x12'\n" +
	"\x10value_at_risk_99\x18\a \x01(\x01R\rvalueAtRisk99\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\xb8\x02\n" +
	"\vRiskMetrics\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1e\n" +
	"\n" +
	"volatility\x18\x02 \x01(\x01R\n" +
	"volatility\x12!\n" +
	"\fsharpe_ratio\x18\x03 \x01(\x01R\vsharpeRatio\x12\x12\n" +
	"\x04beta\x18\x04 \x01(\x01R\x04beta\x12'\n" +
	"\x10value_at_risk_95\x18\x05 \x01(\x01R\rvalueAtRisk95\x12'\n" +
	"\x10value_at_risk_99\x18\x06 \x01(\x01R\rvalueAtRisk99\x12!\n" +
	"\fmax_drawdown\x18\a \x01(\x01R\vmaxDrawdown\x12'\n" +
	"\x0fexpected_return\x18\b \x01(\x01R\x0eexpectedReturn\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\x88\x01\n" +
	"\x0fCorrelationPair\x12\x18\n" +
	"\asymbol1\x18\x01 \x01(\tR\asymbol1\x12\x18\n" +
	"\asymbol2\x18\x02 \x01(\tR\asymbol2\x12 \n" +
	"\vcorrelation\x18\x03 \x01(\x01R\vcorrelation\x12\x1f\n" +
	"\vsample_size\x18\x04 \x01(\x05R\n" +
	"sampleSize\"}\n" +
	"\x11CorrelationMatrix\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x120\n" +
	"\x05pairs\x18\x02 \x03(\v2\x1a.analytics.CorrelationPairR\x05pairs\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xc1\x01\n" +
	"\rTradingSignal\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vsignal_type\x18\x02 \x01(\tR\n" +
	"signalType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\ftarget_price\x18\x05 \x01(\x01R\vtargetPrice\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xdd\x02\n" +
	"\x12PerformanceMetrics\x12\x19\n" +
	"\bapi_type\x18\x01 \x01(\tR\aapiType\x12$\n" +
	"\x0eavg_latency_ms\x18\x02 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\x03 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x04 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x05 \x01(\x01R\fp99LatencyMs\x12#\n" +
	"\rrequest_count\x18\x06 \x01(\x03R\frequestCount\x12%\n" +
	"\x0ethroughput_rps\x18\a \x01(\x01R\rthroughputRps\x12*\n" +
	"\x11avg_payload_bytes\x18\b \x01(\x03R\x0favgPayloadBytes\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp2\xa6\x03\n" +
	"\x10AnalyticsService\x12S\n" +
	"\x15GetPortfolioAnalytics\x12\x1b.analytics.AnalyticsRequest\x1a\x1d.analytics.PortfolioAnalytics\x12G\n" +
	"\x0eGetRiskMetrics\x12\x1b.analytics.AnalyticsRequest\x1a\x16.analytics.RiskMetrics0\x01\x12Q\n" +
	"\x14GetCorrelationMatrix\x12\x1b.analytics.AnalyticsRequest\x1a\x1c.analytics.CorrelationMatrix\x12L\n" +
	"\x11GetTradingSignals\x12\x1b.analytics.AnalyticsRequest\x1a\x18.analytics.TradingSignal0\x01\x12S\n" +
	"\x15GetPerformanceMetrics\x12\x1b.analytics.AnalyticsRequest\x1a\x1d.analytics.PerformanceMetricsB9Z7github.com/Anurag-AV/financial-streaming-platform/protob\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_analytics_proto_goTypes = []any{
	(*AnalyticsRequest)(nil),   // 0: analytics.AnalyticsRequest
	(*PortfolioAnalytics)(nil), // 1: analytics.PortfolioAnalytics
	(*RiskMetrics)(nil),        // 2: analytics.RiskMetrics
	(*CorrelationPair)(nil),    // 3: analytics.CorrelationPair
	(*CorrelationMatrix)(nil),  // 4: analytics.CorrelationMatrix
	(*TradingSignal)(nil),      // 5: analytics.TradingSignal
	(*PerformanceMetrics)(nil), // 6: analytics.PerformanceMetrics
}
var file_proto_analytics_proto_depIdxs = []int32{
	3, // 0: analytics.CorrelationMatrix.pairs:type_name -> analytics.CorrelationPair
	0, // 1: analytics.AnalyticsService.GetPortfolioAnalytics:input_type -> analytics.AnalyticsRequest
	0, // 2: analytics.AnalyticsService.GetRiskMetrics:input_type -> analytics.AnalyticsRequest
	0, // 3: analytics.AnalyticsService.GetCorrelationMatrix:input_type -> analytics.AnalyticsRequest
	0, // 4: analytics.AnalyticsService.GetTradingSignals:input_type -> analytics.AnalyticsRequest
	0, // 5: analytics.AnalyticsService.GetPerformanceMetrics:input_type -> analytics.AnalyticsRequest
	1, // 6: analytics.AnalyticsService.GetPortfolioAnalytics:output_type -> analytics.PortfolioAnalytics
	2, // 7: analytics.AnalyticsService.GetRiskMetrics:output_type -> analytics.RiskMetrics
	4, // 8: analytics.AnalyticsService.GetCorrelationMatrix:output_type -> analytics.CorrelationMatrix
	5, // 9: analytics.AnalyticsService.GetTradingSignals:output_type -> analytics.TradingSignal
	6, // 10: analytics.AnalyticsService.GetPerformanceMetrics:output_type -> analytics.PerformanceMetrics
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	file_proto_processor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
