// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/stock.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_GetStockPrice_FullMethodName        = "/stock.StockService/GetStockPrice"
	StockService_StreamMarketData_FullMethodName     = "/stock.StockService/StreamMarketData"
	StockService_SubscribePriceAlerts_FullMethodName = "/stock.StockService/SubscribePriceAlerts"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stock service definition
type StockServiceClient interface {
	// Simple unary RPC - request one stock price
	GetStockPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockTick, error)
	// Stream continuous market data updates (server streaming RPC)
	StreamMarketData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockTick], error)
	// Subscribe to price alerts (bidirectional streaming)
	SubscribePriceAlerts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PriceAlertRequest, PriceAlert], error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) GetStockPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockTick, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockTick)
	err := c.cc.Invoke(ctx, StockService_GetStockPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) StreamMarketData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockTick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[0], StockService_StreamMarketData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StockTick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamMarketDataClient = grpc.ServerStreamingClient[StockTick]

func (c *stockServiceClient) SubscribePriceAlerts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PriceAlertRequest, PriceAlert], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockService_ServiceDesc.Streams[1], StockService_SubscribePriceAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PriceAlertRequest, PriceAlert]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_SubscribePriceAlertsClient = grpc.BidiStreamingClient[PriceAlertRequest, PriceAlert]

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
//
// Stock service definition
type StockServiceServer interface {
	// Simple unary RPC - request one stock price
	GetStockPrice(context.Context, *StockRequest) (*StockTick, error)
	// Stream continuous market data updates (server streaming RPC)
	StreamMarketData(*StreamRequest, grpc.ServerStreamingServer[StockTick]) error
	// Subscribe to price alerts (bidirectional streaming)
	SubscribePriceAlerts(grpc.BidiStreamingServer[PriceAlertRequest, PriceAlert]) error
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) GetStockPrice(context.Context, *StockRequest) (*StockTick, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockPrice not implemented")
}
func (UnimplementedStockServiceServer) StreamMarketData(*StreamRequest, grpc.ServerStreamingServer[StockTick]) error {
	return status.Error(codes.Unimplemented, "method StreamMarketData not implemented")
}
func (UnimplementedStockServiceServer) SubscribePriceAlerts(grpc.BidiStreamingServer[PriceAlertRequest, PriceAlert]) error {
	return status.Error(codes.Unimplemented, "method SubscribePriceAlerts not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call panics, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_GetStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).GetStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_GetStockPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).GetStockPrice(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_StreamMarketData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockServiceServer).StreamMarketData(m, &grpc.GenericServerStream[StreamRequest, StockTick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_StreamMarketDataServer = grpc.ServerStreamingServer[StockTick]

func _StockService_SubscribePriceAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StockServiceServer).SubscribePriceAlerts(&grpc.GenericServerStream[PriceAlertRequest, PriceAlert]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockService_SubscribePriceAlertsServer = grpc.BidiStreamingServer[PriceAlertRequest, PriceAlert]

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStockPrice",
			Handler:    _StockService_GetStockPrice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketData",
			Handler:       _StockService_StreamMarketData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribePriceAlerts",
			Handler:       _StockService_SubscribePriceAlerts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/stock.proto",
}
