// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/processor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessorService_StreamEnrichedData_FullMethodName = "/processor.ProcessorService/StreamEnrichedData"
	ProcessorService_GetStats_FullMethodName           = "/processor.ProcessorService/GetStats"
)

// ProcessorServiceClient is the client API for ProcessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcessorServiceClient interface {
	// Stream enriched market data with indicators
	StreamEnrichedData(ctx context.Context, in *ProcessorStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnrichedTick], error)
	// Get current statistics
	GetStats(ctx context.Context, in *ProcessorStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessorStats], error)
}

type processorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessorServiceClient(cc grpc.ClientConnInterface) ProcessorServiceClient {
	return &processorServiceClient{cc}
}

func (c *processorServiceClient) StreamEnrichedData(ctx context.Context, in *ProcessorStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnrichedTick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessorService_ServiceDesc.Streams[0], ProcessorService_StreamEnrichedData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessorStreamRequest, EnrichedTick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessorService_StreamEnrichedDataClient = grpc.ServerStreamingClient[EnrichedTick]

func (c *processorServiceClient) GetStats(ctx context.Context, in *ProcessorStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProcessorStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessorService_ServiceDesc.Streams[1], ProcessorService_GetStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessorStreamRequest, ProcessorStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessorService_GetStatsClient = grpc.ServerStreamingClient[ProcessorStats]

// ProcessorServiceServer is the server API for ProcessorService service.
// All implementations must embed UnimplementedProcessorServiceServer
// for forward compatibility.
type ProcessorServiceServer interface {
	// Stream enriched market data with indicators
	StreamEnrichedData(*ProcessorStreamRequest, grpc.ServerStreamingServer[EnrichedTick]) error
	// Get current statistics
	GetStats(*ProcessorStreamRequest, grpc.ServerStreamingServer[ProcessorStats]) error
	mustEmbedUnimplementedProcessorServiceServer()
}

// UnimplementedProcessorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessorServiceServer struct{}

func (UnimplementedProcessorServiceServer) StreamEnrichedData(*ProcessorStreamRequest, grpc.ServerStreamingServer[EnrichedTick]) error {
	return status.Error(codes.Unimplemented, "method StreamEnrichedData not implemented")
}
func (UnimplementedProcessorServiceServer) GetStats(*ProcessorStreamRequest, grpc.ServerStreamingServer[ProcessorStats]) error {
	return status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedProcessorServiceServer) mustEmbedUnimplementedProcessorServiceServer() {}
func (UnimplementedProcessorServiceServer) testEmbeddedByValue()                          {}

// UnsafeProcessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessorServiceServer will
// result in compilation errors.
type UnsafeProcessorServiceServer interface {
	mustEmbedUnimplementedProcessorServiceServer()
}

func RegisterProcessorServiceServer(s grpc.ServiceRegistrar, srv ProcessorServiceServer) {
	// If the following call panics, it indicates UnimplementedProcessorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessorService_ServiceDesc, srv)
}

func _ProcessorService_StreamEnrichedData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessorStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessorServiceServer).StreamEnrichedData(m, &grpc.GenericServerStream[ProcessorStreamRequest, EnrichedTick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessorService_StreamEnrichedDataServer = grpc.ServerStreamingServer[EnrichedTick]

func _ProcessorService_GetStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProcessorStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessorServiceServer).GetStats(m, &grpc.GenericServerStream[ProcessorStreamRequest, ProcessorStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessorService_GetStatsServer = grpc.ServerStreamingServer[ProcessorStats]

// ProcessorService_ServiceDesc is the grpc.ServiceDesc for ProcessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processor.ProcessorService",
	HandlerType: (*ProcessorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEnrichedData",
			Handler:       _ProcessorService_StreamEnrichedData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStats",
			Handler:       _ProcessorService_GetStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/processor.proto",
}
