// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/processor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enriched stock data with calculated indicators
type EnrichedTick struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Original tick data
	Tick *StockTick `protobuf:"bytes,1,opt,name=tick,proto3" json:"tick,omitempty"`
	// Technical indicators
	Vwap      float64 `protobuf:"fixed64,2,opt,name=vwap,proto3" json:"vwap,omitempty"`                         // Volume Weighted Average Price
	Sma_5Min  float64 `protobuf:"fixed64,3,opt,name=sma_5min,json=sma5min,proto3" json:"sma_5min,omitempty"`    // 5-minute Simple Moving Average
	Sma_15Min float64 `protobuf:"fixed64,4,opt,name=sma_15min,json=sma15min,proto3" json:"sma_15min,omitempty"` // 15-minute Simple Moving Average
	Ema_5Min  float64 `protobuf:"fixed64,5,opt,name=ema_5min,json=ema5min,proto3" json:"ema_5min,omitempty"`    // 5-minute Exponential Moving Average
	Ema_15Min float64 `protobuf:"fixed64,6,opt,name=ema_15min,json=ema15min,proto3" json:"ema_15min,omitempty"` // 15-minute Exponential Moving Average
	// Bollinger Bands
	BollingerUpper  float64 `protobuf:"fixed64,7,opt,name=bollinger_upper,json=bollingerUpper,proto3" json:"bollinger_upper,omitempty"`    // Upper band (SMA + 2*StdDev)
	BollingerMiddle float64 `protobuf:"fixed64,8,opt,name=bollinger_middle,json=bollingerMiddle,proto3" json:"bollinger_middle,omitempty"` // Middle band (SMA)
	BollingerLower  float64 `protobuf:"fixed64,9,opt,name=bollinger_lower,json=bollingerLower,proto3" json:"bollinger_lower,omitempty"`    // Lower band (SMA - 2*StdDev)
	// Volatility metrics
	Volatility    float64 `protobuf:"fixed64,10,opt,name=volatility,proto3" json:"volatility,omitempty"`                            // Recent price volatility
	PriceMomentum float64 `protobuf:"fixed64,11,opt,name=price_momentum,json=priceMomentum,proto3" json:"price_momentum,omitempty"` // Rate of price change
	// Anomaly flags
	IsAnomaly     bool    `protobuf:"varint,12,opt,name=is_anomaly,json=isAnomaly,proto3" json:"is_anomaly,omitempty"`           // Unusual price movement detected
	AnomalyType   string  `protobuf:"bytes,13,opt,name=anomaly_type,json=anomalyType,proto3" json:"anomaly_type,omitempty"`      // "SPIKE", "DROP", "VOLATILITY", etc.
	AnomalyScore  float64 `protobuf:"fixed64,14,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"` // Severity score (0-1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedTick) Reset() {
	*x = EnrichedTick{}
	mi := &file_proto_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedTick) ProtoMessage() {}

func (x *EnrichedTick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedTick.ProtoReflect.Descriptor instead.
func (*EnrichedTick) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichedTick) GetTick() *StockTick {
	if x != nil {
		return x.Tick
	}
	return nil
}

func (x *EnrichedTick) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *EnrichedTick) GetSma_5Min() float64 {
	if x != nil {
		return x.Sma_5Min
	}
	return 0
}

func (x *EnrichedTick) GetSma_15Min() float64 {
	if x != nil {
		return x.Sma_15Min
	}
	return 0
}

func (x *EnrichedTick) GetEma_5Min() float64 {
	if x != nil {
		return x.Ema_5Min
	}
	return 0
}

func (x *EnrichedTick) GetEma_15Min() float64 {
	if x != nil {
		return x.Ema_15Min
	}
	return 0
}

func (x *EnrichedTick) GetBollingerUpper() float64 {
	if x != nil {
		return x.BollingerUpper
	}
	return 0
}

func (x *EnrichedTick) GetBollingerMiddle() float64 {
	if x != nil {
		return x.BollingerMiddle
	}
	return 0
}

func (x *EnrichedTick) GetBollingerLower() float64 {
	if x != nil {
		return x.BollingerLower
	}
	return 0
}

func (x *EnrichedTick) GetVolatility() float64 {
	if x != nil {
		return x.Volatility
	}
	return 0
}

func (x *EnrichedTick) GetPriceMomentum() float64 {
	if x != nil {
		return x.PriceMomentum
	}
	return 0
}

func (x *EnrichedTick) GetIsAnomaly() bool {
	if x != nil {
		return x.IsAnomaly
	}
	return false
}

func (x *EnrichedTick) GetAnomalyType() string {
	if x != nil {
		return x.AnomalyType
	}
	return ""
}

func (x *EnrichedTick) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

// Request to subscribe to processed data stream
type ProcessorStreamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbols         []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`                                           // Which symbols to process
	IncludeRawTicks bool                   `protobuf:"varint,2,opt,name=include_raw_ticks,json=includeRawTicks,proto3" json:"include_raw_ticks,omitempty"` // Include unprocessed ticks?
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessorStreamRequest) Reset() {
	*x = ProcessorStreamRequest{}
	mi := &file_proto_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorStreamRequest) ProtoMessage() {}

func (x *ProcessorStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorStreamRequest.ProtoReflect.Descriptor instead.
func (*ProcessorStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessorStreamRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ProcessorStreamRequest) GetIncludeRawTicks() bool {
	if x != nil {
		return x.IncludeRawTicks
	}
	return false
}

// Statistics summary
type ProcessorStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Symbol              string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TicksProcessed      int64                  `protobuf:"varint,2,opt,name=ticks_processed,json=ticksProcessed,proto3" json:"ticks_processed,omitempty"`
	AnomaliesDetected   int64                  `protobuf:"varint,3,opt,name=anomalies_detected,json=anomaliesDetected,proto3" json:"anomalies_detected,omitempty"`
	AvgProcessingTimeMs float64                `protobuf:"fixed64,4,opt,name=avg_processing_time_ms,json=avgProcessingTimeMs,proto3" json:"avg_processing_time_ms,omitempty"`
	Timestamp           int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessorStats) Reset() {
	*x = ProcessorStats{}
	mi := &file_proto_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorStats) ProtoMessage() {}

func (x *ProcessorStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorStats.ProtoReflect.Descriptor instead.
func (*ProcessorStats) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessorStats) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ProcessorStats) GetTicksProcessed() int64 {
	if x != nil {
		return x.TicksProcessed
	}
	return 0
}

func (x *ProcessorStats) GetAnomaliesDetected() int64 {
	if x != nil {
		return x.AnomaliesDetected
	}
	return 0
}

func (x *ProcessorStats) GetAvgProcessingTimeMs() float64 {
	if x != nil {
		return x.AvgProcessingTimeMs
	}
	return 0
}

func (x *ProcessorStats) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_processor_proto protoreflect.FileDescriptor

const file_proto_processor_proto_rawDesc = "" +
	"\n" +
	"\x15proto/processor.proto\x12\tprocessor\x1a\x11proto/stock.proto\"\xe3\x03\n" +
	"\fEnrichedTick\x12$\n" +
	"\x04tick\x18\x01 \x01(\v2\x10.stock.StockTickR\x04tick\x12\x12\n" +
	"\x04vwap\x18\x02 \x01(\x01R\x04vwap\x12\x19\n" +
	"\bsma_5min\x18\x03 \x01(\x01R\asma5min\x12\x1b\n" +
	"\tsma_15min\x18\x04 \x01(\x01R\bsma15min\x12\x19\n" +
	"\bema_5min\x18\x05 \x01(\x01R\aema5min\x12\x1b\n" +
	"\tema_15min\x18\x06 \x01(\x01R\bema15min\x12'\n" +
	"\x0fbollinger_upper\x18\a \x01(\x01R\x0ebollingerUpper\x12)\n" +
	"\x10bollinger_middle\x18\b \x01(\x01R\x0fbollingerMiddle\x12'\n" +
	"\x0fbollinger_lower\x18\t \x01(\x01R\x0ebollingerLower\x12\x1e\n" +
	"\n" +
	"volatility\x18\n" +
	" \x01(\x01R\n" +
	"volatility\x12%\n" +
	"\x0eprice_momentum\x18\v \x01(\x01R\rpriceMomentum\x12\x1d\n" +
	"\n" +
	"is_anomaly\x18\f \x01(\bR\tisAnomaly\x12!\n" +
	"\fanomaly_type\x18\r \x01(\tR\vanomalyType\x12#\n" +
	"\ranomaly_score\x18\x0e \x01(\x01R\fanomalyScore\"^\n" +
	"\x16ProcessorStreamRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12*\n" +
	"\x11include_raw_ticks\x18\x02 \x01(\bR\x0fincludeRawTicks\"\xd3\x01\n" +
	"\x0eProcessorStats\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x0fticks_processed\x18\x02 \x01(\x03R\x0eticksProcessed\x12-\n" +
	"\x12anomalies_detected\x18\x03 \x01(\x03R\x11anomaliesDetected\x123\n" +
	"\x16avg_processing_time_ms\x18\x04 \x01(\x01R\x13avgProcessingTimeMs\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\xb2\x01\n" +
	"\x10ProcessorService\x12R\n" +
	"\x12StreamEnrichedData\x12!.processor.ProcessorStreamRequest\x1a\x17.processor.EnrichedTick0\x01\x12J\n" +
	"\bGetStats\x12!.processor.ProcessorStreamRequest\x1a\x19.processor.ProcessorStats0\x01B9Z7github.com/Anurag-AV/financial-streaming-platform/protob\x06proto3"

var (
	file_proto_processor_proto_rawDescOnce sync.Once
	file_proto_processor_proto_rawDescData []byte
)

func file_proto_processor_proto_rawDescGZIP() []byte {
	file_proto_processor_proto_rawDescOnce.Do(func() {
		file_proto_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processor_proto_rawDesc), len(file_proto_processor_proto_rawDesc)))
	})
	return file_proto_processor_proto_rawDescData
}

var file_proto_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_processor_proto_goTypes = []any{
	(*EnrichedTick)(nil),           // 0: processor.EnrichedTick
	(*ProcessorStreamRequest)(nil), // 1: processor.ProcessorStreamRequest
	(*ProcessorStats)(nil),         // 2: processor.ProcessorStats
	(*StockTick)(nil),              // 3: stock.StockTick
}
var file_proto_processor_proto_depIdxs = []int32{
	3, // 0: processor.EnrichedTick.tick:type_name -> stock.StockTick
	1, // 1: processor.ProcessorService.StreamEnrichedData:input_type -> processor.ProcessorStreamRequest
	1, // 2: processor.ProcessorService.GetStats:input_type -> processor.ProcessorStreamRequest
	0, // 3: processor.ProcessorService.StreamEnrichedData:output_type -> processor.EnrichedTick
	2, // 4: processor.ProcessorService.GetStats:output_type -> processor.ProcessorStats
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_processor_proto_init() }
func file_proto_processor_proto_init() {
	if File_proto_processor_proto != nil {
		return
	}
	file_proto_stock_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processor_proto_rawDesc), len(file_proto_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_processor_proto_goTypes,
		DependencyIndexes: file_proto_processor_proto_depIdxs,
		MessageInfos:      file_proto_processor_proto_msgTypes,
	}.Build()
	File_proto_processor_proto = out.File
	file_proto_processor_proto_goTypes = nil
	file_proto_processor_proto_depIdxs = nil
}
