// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/stock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting stock price
type StockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	mi := &file_proto_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Stock tick data with financial details
type StockTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                               // Stock symbol (e.g., "AAPL")
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`                               // Current price
	Volume        int64                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`                              // Trade volume
	Bid           float64                `protobuf:"fixed64,4,opt,name=bid,proto3" json:"bid,omitempty"`                                   // Bid price
	Ask           float64                `protobuf:"fixed64,5,opt,name=ask,proto3" json:"ask,omitempty"`                                   // Ask price
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                        // Unix timestamp (nanoseconds)
	TradeType     string                 `protobuf:"bytes,7,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`        // "BUY" or "SELL"
	MarketDepth   int32                  `protobuf:"varint,8,opt,name=market_depth,json=marketDepth,proto3" json:"market_depth,omitempty"` // Number of orders in book
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockTick) Reset() {
	*x = StockTick{}
	mi := &file_proto_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTick) ProtoMessage() {}

func (x *StockTick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTick.ProtoReflect.Descriptor instead.
func (*StockTick) Descriptor() ([]byte, []int) {
	return file_proto_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockTick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockTick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockTick) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *StockTick) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *StockTick) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *StockTick) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StockTick) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *StockTick) GetMarketDepth() int32 {
	if x != nil {
		return x.MarketDepth
	}
	return 0
}

var File_proto_stock_proto protoreflect.FileDescriptor

const file_proto_stock_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stock.proto\x12\x05stock\"&\n" +
	"\fStockRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xd5\x01\n" +
	"\tStockTick\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x03R\x06volume\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x05 \x01(\x01R\x03ask\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"trade_type\x18\a \x01(\tR\ttradeType\x12!\n" +
	"\fmarket_depth\x18\b \x01(\x05R\vmarketDepth2F\n" +
	"\fStockService\x126\n" +
	"\rGetStockPrice\x12\x13.stock.StockRequest\x1a\x10.stock.StockTickB9Z7github.com/Anurag-AV/financial-streaming-platform/protob\x06proto3"

var (
	file_proto_stock_proto_rawDescOnce sync.Once
	file_proto_stock_proto_rawDescData []byte
)

func file_proto_stock_proto_rawDescGZIP() []byte {
	file_proto_stock_proto_rawDescOnce.Do(func() {
		file_proto_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stock_proto_rawDesc), len(file_proto_stock_proto_rawDesc)))
	})
	return file_proto_stock_proto_rawDescData
}

var file_proto_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stock_proto_goTypes = []any{
	(*StockRequest)(nil), // 0: stock.StockRequest
	(*StockTick)(nil),    // 1: stock.StockTick
}
var file_proto_stock_proto_depIdxs = []int32{
	0, // 0: stock.StockService.GetStockPrice:input_type -> stock.StockRequest
	1, // 1: stock.StockService.GetStockPrice:output_type -> stock.StockTick
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stock_proto_init() }
func file_proto_stock_proto_init() {
	if File_proto_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stock_proto_rawDesc), len(file_proto_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stock_proto_goTypes,
		DependencyIndexes: file_proto_stock_proto_depIdxs,
		MessageInfos:      file_proto_stock_proto_msgTypes,
	}.Build()
	File_proto_stock_proto = out.File
	file_proto_stock_proto_goTypes = nil
	file_proto_stock_proto_depIdxs = nil
}
